// Gallery images for the About page

export const aboutGalleryImages = [
  { src: "/gallery-about/opening-day-2019.jpg", alt: "Opening Day 2019" },
  { src: "/gallery-about/xtreem13.jpg", alt: "IEEE Xtreme 13.0" },
  { src: "/gallery-about/crieee-day-1.jpg", alt: "CRIEEE DAY 1.0" },
  { src: "/gallery-about/integration-day-2021.jpg", alt: "Integration Day 2021" },
  { src: "/gallery-about/progress-day-2021.jpg", alt: "Progress Day 2021" },
  { src: "/gallery-about/AG-2021.jpg", alt: "General Assembly 2021" },
  { src: "/gallery-about/crieee-day-2.jpg", alt: "CRIEEE DAY 2.0" },
  { src: "/gallery-about/integration-day-2022.jpg", alt: "Integration DAY 2022" },
  { src: "/gallery-about/ieee-day-2023.jpg", alt: "IEEE DAY 2023" },
  { src: "/gallery-about/xtreem16.jpg", alt: "IEEE Xtreme 16.0" },
  { src: "/gallery-about/crieee-day-3.jpg", alt: "CRIEEE DAY 3.0" },
  { src: "/gallery-about/tsyp-x.jpg", alt: "TSYP X" },
  { src: "/gallery-about/team-building.jpg", alt: "Team Building" },
  { src: "/gallery-about/birthday-2023.jpg", alt: "4th Birthday" },
  { src: "/gallery-about/games-night.jpg", alt: "Games Night" },
  { src: "/gallery-about/crieee-challenge.png", alt: "CRIEEE Challenge" },
  { src: "/gallery-about/internal-pitching competition.jpg", alt: "Internal Pitching Competition 1.0" },
  { src: "/gallery-about/integration-day-2023.jpg", alt: "Integration DAY 2023" },
  { src: "/gallery-about/birthday-2024.jpg", alt: "5th Birthday" },
  { src: "/gallery-about/cs-for-entreprise-summit.png", alt: "CS for entreprise summit" },
  { src: "/gallery-about/internal-pitching competition 2.jpg", alt: "Internal Pitching Competition 2.0" },
  { src: "/gallery-about/ieee-day-2024.jpg", alt: "IEEE DAY 2024" },
  { src: "/gallery-about/who-are-we-2.jpg", alt: "WHO ARE WE 2.0" },
  { src: "/gallery-about/internal-bootcamp-1.jpg", alt: "Internal Bootcamp" },
  { src: "/gallery-about/internal-bootcamp-2.jpg", alt: "Internal Bootcamp" },
  { src: "/gallery-about/internal-bootcamp-3.jpg", alt: "Internal Bootcamp" },
  { src: "/gallery-about/5th-birthday.jpg", alt: "5th Birthday" },
];